website/models.py
from . import db
from flask_login import UserMixin

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password_hash = db.Column(db.String(200))

  

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'chenyu_is_shuaige'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///Alex.db'
    db.init_app(app)

    with app.app_context():
        from .models import User 
        db.create_all()


    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        from .models import User
        return User.query.get(int(user_id))

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    return app

def load_user(user_id):
    return User.query.get(int(user_id))

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required
from .models import User
from . import db
from werkzeug.security import generate_password_hash

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')  
        password = request.form.get('password') 

        user = User.query.filter_by(username=username).first()  

        if user and check_password_hash(user.password_hash, password):  
            login_user(user, remember=True) 
            return redirect(url_for('auth.home'))  
        else:
            flash('Please check your login details and try again.')

    return render_template('login.html') 


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return "<p>Logout</p>"


@auth.route('/sign-up', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')

        if not password:
            return render_template('sign_up.html', error="Password is required.")
        
        hashed_password = generate_password_hash(password, method='pbkdf2:sha256')

        new_user = User(username=username, email=email, password_hash=hashed_password)
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('auth.login'))

    return render_template('sign_up.html')



@auth.route('/home')
def home():
    return render_template("home.html")

website/views.py
from flask import Blueprint, render_template
from . import db

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html")

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"
      />

    </head>
    <body>


      <!-- Button to trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Open Modal
</button>





<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/home">Food Link</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" id="home" href="/home">Home</a></li>
      <li class="nav-item"><a class="nav-link" id="login" href="/login">Login</a></li>
      <li class="nav-item"><a class="nav-link" id="signUp" href="/sign-up">Sign Up</a></li>
      <li class="nav-item"><a class="nav-link" id="logout" href="/logout">Logout</a></li>
  </ul>
  </div>
</nav>

    
        <div class="container">
          <h1>Food Link - CS 411 Project</h1>
        </div>
      <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
      ></script>

      <script
        type="text/javascript"
        src="{{url_for('static', filename='index.js')}}"
            
      ></script>
    </body>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-dark text-white text-center">
      <div class="container">
          <span>&copy; 2024 Food Link - CS 411 Project. All Rights Reserved.</span>
      </div>
  </footer>
</html>

website/templates/home.html
{% block content %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCGkDFRGKLkyK_V2BIqTsrp_BiD-8Eo1-8&callback=initMap" async defer></script>
    <title>Food Link - CS 411 Project</title>

</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/home">Food Link</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" id="home" href="/home">Home</a></li>
                <li class="nav-item"><a class="nav-link" id="login" href="/login">Login</a></li>
                <li class="nav-item"><a class="nav-link" id="signUp" href="/sign-up">Sign Up</a></li>
                <li class="nav-item"><a class="nav-link" id="logout" href="/logout">Logout</a></li>
            </ul>
        </div>
    </nav>

    <!-- Main Container -->
    <div class="container mt-4">
     

    <!-- Input and check box -->
    <section id="recipe-search">
        <h2 class="text-info">Find a Recipe</h2>

        <div class="container">
        <div class="row g-3">
        <div class="col-md-6">
            <div class="input-group mb-3 text-info">
            <!-- input food description -->
            <form onsubmit="fetchRecipes(event)">
                <div class="input-group-append">
                    <input type="text" name="q" placeholder="Search for recipes..." required="required" class="form-control" aria-label="Recipient's username" aria-describedby="button-addon2" oninput="searchPlaces(this.value)">
                    <button class="btn btn-outline-info" type="submit">Search</button>
                </div>
            </form>
        </div></div>
        <div class="col-md-1"></div>
        <div class="col-md-5">
        <div class="d-flex justify-content-center align-items-center h-50">
            <!-- input city or zipcode -->
            <input type="text" id="zipcode" class="form-control" placeholder="Enter city or zipcode" aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-outline-info" type="button" id="search-restaurant-button" onclick="searchRestaurant()">Search</button>
        </div>

            <!-- check box -->
        <div class="d-flex align-items-center h-50">
            <div class="form-check">
            <input class="form-check-input" type="checkbox" id="check1">
            <label class="form-check-label" for="gridCheck">
                Food Pantries
            </label>
            </div>
            <div class="px-3"></div>
            <div class="form-check">
            <input class="form-check-input" type="checkbox" id="check2">
            <label class="form-check-label" for="gridCheck">
                Community Meal Program
            </label>
        </div></div>
        </div>
    </section>
    <div class="mb-4"></div>


    <div class="container">
    <div class="row">
    <div class="col-md-6">
    <section id="nutritional-info">
        <!-- Nutritional information will be displayed here upon selecting a recipe -->
        <h2 class="text-info">Nutritional Information</h2>
        <div class="border p-3 bg-light text-info">
            <p id="recipe"> Tell us some discriptions to get respond. </p>
        </div>
    </section></div>

    <div class="col-md-1"></div>

    <div class="col-md-5">
    <section id="recipe-results">
        <!-- Results from the recipe API will be displayed here -->
        <!-- chatgpt respond -->
        <h2 class="text-info">Recipe Suggestions</h2>
        <div class="border p-3 bg-light text-info">
            <p id="chatgpt">Tell us some discriptions to get respond. </p>
        </div> 
    </section></div></div>
    <div class="mb-4"></div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </div>


    <section id="map">
        <h2 class="text-info">Nearby Restaurants</h2>
        <div id="google-map" style="height: 400px; width: 98%;">
            <!-- Google Maps will be rendered here -->
        </div>
        
    </section>
    <div class="mb-5"></div>


    </div>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-dark text-white text-center">
        <div class="container">
            <span>&copy; 2024 Food Link - CS 411 Project. All Rights Reserved.</span>
        </div>
    </footer>

    
    <script>
    let map;
    let service;
    let infowindow;
    let userLocation;
    let markers = [];

    function initMap() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                userLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
                map = new google.maps.Map(document.getElementById('google-map'), {
                    center: userLocation,
                    zoom: 12
                });
                infowindow = new google.maps.InfoWindow();
            }, function() {
                handleLocationError(true, infowindow, map.getCenter());
            });
        } else {
            // Browser doesn't support Geolocation
            handleLocationError(false, infowindow, map.getCenter());
        }
    }

    function searchPlaces(query) {
        const request = {
            location: userLocation || map.getCenter(),
            radius: '5000',
            type: ['restaurant'],
            keyword: query
        };

        service = new google.maps.places.PlacesService(map);
        service.textSearch(request, callback);
    }

    function callback(results, status) {
        if (status === google.maps.places.PlacesServiceStatus.OK) {
            clearMarkers();  // Clear existing markers before adding new ones
            results.forEach(createMarker);
        }
    }

    function createMarker(place) {
        if (!place.geometry || !place.geometry.location) return;

        const marker = new google.maps.Marker({
            map: map,
            position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', () => {
            infowindow.setContent('<div><strong>' + place.name + '</strong><br>' +
                'Place ID: ' + place.place_id + '<br>' +
                place.formatted_address + '</div>');
            infowindow.open(map, marker);
        });
        markers.push(marker);  // Add the marker to the array of markers
    }

    function clearMarkers() {
        // Clear all markers from the map
        for (let marker of markers) {
            marker.setMap(null);
        }
        markers = [];
    }
        </script>
        <script>
            async function fetchRecipes(event) {
                event.preventDefault();
                const query = document.querySelector('[name="q"]').value;
                const url = `https://api.spoonacular.com/recipes/complexSearch?query=${query}&addRecipeNutrition=true&apiKey=90a3e0792e3147c296c05171ed7aaa47`;
                const response = await fetch(url);
                const data = await response.json();
                displayRecipes(data.results);
                displayNutritionalInfo(data.results[0]);
            }
            async function showRecipeDetails(recipeId) {
                const recipeUrl = `https://api.spoonacular.com/recipes/${recipeId}/information?apiKey=90a3e0792e3147c296c05171ed7aaa47`;
                const response = await fetch(recipeUrl);
                const recipeDetails = await response.json();

                displayIngredients(recipeDetails);
                searchPlaces(recipeDetails.title); // This assumes that the restaurant search is related to the recipe title
            }
            function displayRecipes(recipes) {
                const container = document.getElementById('chatgpt');
                container.innerHTML = recipes.map(recipe => 
                `<div onclick="showRecipeDetails(${recipe.id})" style="cursor: pointer;">${recipe.title}</div>`
                ).join('');
            }
    
            function displayIngredients(recipe) {
                const info = document.getElementById('recipe');
                const ingredients = recipe.extendedIngredients.map(ing => ing.original).join('<br>');
                info.innerHTML = `<strong>Ingredients:</strong><br>${ingredients}`;
            }

        </script>
    <!-- JavaScript -->
    <script type="text/javascript" src="{{ url_for('static', filename='app.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
    <!-- Google Maps API -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCGkDFRGKLkyK_V2BIqTsrp_BiD-8Eo1-8&callback=initMap" async defer></script>

</body>
{% endblock %}

website/templates/login.html
{% block content %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
    <meta name="google-signin-client_id" content="1049791147934-icdtst7v5qovtasrnfppspl2irpg2p9u.apps.googleusercontent.com">
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('views.home') }}">Food Link</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{{ url_for('views.home') }}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        <h1>Login to Your Account</h1>
        <!-- Flash messages display area -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <form id="loginForm" method="POST" action="{{ url_for('auth.login') }}">
            <div class="form-group">
                <label for="username">Username:</label>
                <input 
                    type="text" 
                    class="form-control" 
                    id="username" 
                    name="username" 
                    style="width: 200px;" 
                    placeholder="Enter username" 
                    required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input 
                    type="password" 
                    class="form-control" 
                    id="password" 
                    name="password" 
                    style="width: 500px;" 
                    placeholder="Enter password" 
                    required>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
            
        </form>
        <div id="my-signin2"></div>
        <script>
          function onSuccess(googleUser) {
            console.log('Logged in as: ' + googleUser.getBasicProfile().getName());
          }
          function onFailure(error) {
            console.log(error);
          }
          function renderButton() {
            gapi.signin2.render('my-signin2', {
              'scope': 'profile email',
              'width': 240,
              'height': 50,
              'longtitle': true,
              'theme': 'dark',
              'onsuccess': onSuccess,
              'onfailure': onFailure
            });
          }
        </script>
        <div id="message"></div>
        
    </div>
  
    <script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
</body>
{% endblock %}

website/templates/sign_up.html
{% block content %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/home">Food Link</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" id="home" href="/home">Home</a></li>
                <li class="nav-item"><a class="nav-link" id="login" href="/login">Login</a></li>
                <li class="nav-item"><a class="nav-link" id="signUp" href="/sign-up">Sign Up</a></li>
                <li class="nav-item"><a class="nav-link" id="logout" href="/logout">Logout</a></li>
            </ul>
        </div>
    </nav>
</body>
<div class="container mt-4">
    <form method="POST">
        <h1>Sign Up</h1>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input 
                type="email" 
                class="form-control" 
                id="email" 
                name="email" 
                placeholder="Enter email"
                style="width: 500px;"
            />
        </div>
        <div class="form-group">
            <label for="username">Username</label>
            <input 
                type="text" 
                class="form-control" 
                id="username" 
                name="username" 
                placeholder="Enter username"
                style="width: 200px;"
            />
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input 
                type="password" 
                class="form-control" 
                id="password" 
                name="password" 
                placeholder="Enter password"
                style="width: 500px;"
            />
        </div>
        <div class="form-group">
            <label for="password2">Password (Confirm)</label>
            <input 
                type="password" 
                class="form-control" 
                id="password2" 
                name="password2" 
                placeholder="Confirm password"
                style="width: 500px;"
            />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    

</div>

{% endblock %}